package tw.skyarrow.ehreader.db;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table IMAGE_SEARCH.
 */
public class ImageSearch {

    private Long id;
    private String path;

    public ImageSearch() {
    }

    public ImageSearch(Long id) {
        this.id = id;
    }

    public ImageSearch(Long id, String path) {
        this.id = id;
        this.path = path;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getPath() {
        return path;
    }

    public void setPath(String path) {
        this.path = path;
    }

}
